version: '3.8'

services:
  gosa:
    build: .
    container_name: gosa-fpm
    restart: unless-stopped
    environment:
      - LDAP_SERVER=ldap://openldap:389
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_ADMIN_PASSWORD=admin_secret
      - GOSA_ADMIN_PASSWORD=gosa_secret
    volumes:
      - gosa_data:/var/lib/gosa
      - gosa_cache:/var/cache/gosa
      - gosa_spool:/var/spool/gosa
    depends_on:
      - openldap
    networks:
      - gosa-network

  nginx:
    image: nginx:alpine
    container_name: gosa-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/gosa.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gosa
    networks:
      - gosa-network

  openldap:
    image: osixia/openldap:latest
    container_name: gosa-ldap
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION="Example Corp"
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin_secret
      - LDAP_CONFIG_PASSWORD=config_secret
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      - gosa-network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: gosa-phpldapadmin
    restart: unless-stopped
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - gosa-network

volumes:
  gosa_data:
  gosa_cache:
  gosa_spool:
  ldap_data:
  ldap_config:

networks:
  gosa-network:
    driver: bridge

